=== brimbellelab/brimbellePass/XML_samples/pwdList.dtd
<!ELEMENT pwdList (entree*)>

<!ELEMENT entry (password, oldPassword*, safetyAnswer*, misc*)>
<!-- The key to bind every entry with the matching logins entry-->
<!ATTLIST entry id CDATA #REQUIRED)>

<!ELEMENT password (#PCDATA)>
<!ELEMENT oldPassword (#PCDATA)>
<!ELEMENT safetyAnswer (#PCDATA)>
<!ATTLIST safetyAnswer index CDATA #REQUIRED)>
<!ELEMENT misc (#PCDATA)>

=== brimbellelab/brimbellePass/XML_samples/pwdList.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>

<!DOCTYPE pwdList SYSTEM "pwdList.dtd">

<pwdList>
    <entry id = "1">
        <password>qjVsiXsAsBiS700OK03Xig==</password>
        <oldPassword>gjzdwZ8LNGmyXlpKWjLbyQ==</oldPassword>
    </entry>
    <entry id = "2">
        <password>Dm07NcrX24v5+mysiyRlbQ==</password>
        <oldPassword>VkBYSbpj2kNF0o3vZThJ3A==</oldPassword>
        <safetyAnswer index="0">ccHoSvRuLle+ii3HOZr/rQ==</safetyAnswer>
        <safetyAnswer index="1">PgKhIdWY6XkeIFuK9wzImz/Xv0VRLqobOZUjzc3Hlsg=</safetyAnswer>
        <safetyAnswer index="2">JI62WsIE2yBVYKnXWT2F1g==</safetyAnswer>
    </entry>
    <entry id = "3">
        <password>4/+r+tyN/3+DNaei86UcjA==</password>
        <oldPassword>ginKCB+vf4jYiLKbMhZEFw==</oldPassword>
        <safetyAnswer index="0">BGDKPyJHpB+ScIscGrG2Sw==</safetyAnswer>
        <safetyAnswer index="1">xbAJEU6hK5+FhQuInFocFKaHG9P3LK7fkphkcsle4do=</safetyAnswer>
        <safetyAnswer index="2">W+s5zIc7gL18W5m07t2rXw==</safetyAnswer>
    </entry>
    <entry id = "4">
        <password>4/+r+tyN/3+DNaei86UcjA==</password>
        <safetyAnswer index="0">EvGss/Y08qUJo3vykLM/LH1rXU+kTjvXs/KdCt5Og1TxQWMg8smqx3sbVwVljlpw</safetyAnswer>
        <safetyAnswer index="1">blkKyHemTmxQtKKQxfBTNl3E8Svm/bt2IzWrzfJBUA8=</safetyAnswer>
        <safetyAnswer index="2">qBSbJzeeZ6k58xgBAUajc6HPyJAmPF/8HGs5opsd8w+6zbO9VZOWZfSI3yDi+DRVgSm5J0/1rLFpE9QqjAkpjw==</safetyAnswer>
    </entry>
</pwdList>
